// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// rp2040linesensor //
// ---------------- //

#define rp2040linesensor_wrap_target 0
#define rp2040linesensor_wrap 25
#define rp2040linesensor_pio_version 0

static const uint16_t rp2040linesensor_program_instructions[] = {
            //     .wrap_target
    0xa043, //  0: mov    y, null
    0xa0eb, //  1: mov    osr, ~null
    0x6005, //  2: out    pins, 5
    0x6085, //  3: out    pindirs, 5
    0x6048, //  4: out    y, 8
    0xad42, //  5: nop                           [13]
    0x0085, //  6: jmp    y--, 5
    0xa043, //  7: mov    y, null
    0xe080, //  8: set    pindirs, 0
    0xa0eb, //  9: mov    osr, ~null
    0x604f, // 10: out    y, 15
    0xa020, // 11: mov    x, pins
    0xa0e2, // 12: mov    osr, y
    0xa040, // 13: mov    y, pins
    0x00b2, // 14: jmp    x != y, 18
    0xa047, // 15: mov    y, osr
    0x008c, // 16: jmp    y--, 12
    0x0018, // 17: jmp    24
    0xa022, // 18: mov    x, y
    0x4045, // 19: in     y, 5
    0xa047, // 20: mov    y, osr
    0x40ef, // 21: in     osr, 15
    0x0038, // 22: jmp    !x, 24
    0x008c, // 23: jmp    y--, 12
    0xa04b, // 24: mov    y, ~null
    0x4040, // 25: in     y, 32
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rp2040linesensor_program = {
    .instructions = rp2040linesensor_program_instructions,
    .length = 26,
    .origin = -1,
    .pio_version = rp2040linesensor_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rp2040linesensor_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rp2040linesensor_wrap_target, offset + rp2040linesensor_wrap);
    return c;
}
#endif

