// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// rp2040encoder //
// ------------- //

#define rp2040encoder_wrap_target 19
#define rp2040encoder_wrap 29
#define rp2040encoder_pio_version 0

#define rp2040encoder_offset_entry_point 16u

static const uint16_t rp2040encoder_program_instructions[] = {
    0x001c, //  0: jmp    28
    0x0017, //  1: jmp    23
    0x001b, //  2: jmp    27
    0x001c, //  3: jmp    28
    0x001b, //  4: jmp    27
    0x001c, //  5: jmp    28
    0x001c, //  6: jmp    28
    0x0017, //  7: jmp    23
    0x0017, //  8: jmp    23
    0x001c, //  9: jmp    28
    0x001c, // 10: jmp    28
    0x001b, // 11: jmp    27
    0x001c, // 12: jmp    28
    0x001b, // 13: jmp    27
    0x0017, // 14: jmp    23
    0x001c, // 15: jmp    28
    0xa040, // 16: mov    y, pins
    0xa023, // 17: mov    x, null
    0xa0c3, // 18: mov    isr, null
            //     .wrap_target
    0x4042, // 19: in     y, 2
    0xa040, // 20: mov    y, pins
    0x4042, // 21: in     y, 2
    0xa0a6, // 22: mov    pc, isr
    0xa029, // 23: mov    x, ~x
    0x0059, // 24: jmp    x--, 25
    0xa029, // 25: mov    x, ~x
    0x001c, // 26: jmp    28
    0x005c, // 27: jmp    x--, 28
    0xa0c1, // 28: mov    isr, x
    0x8000, // 29: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rp2040encoder_program = {
    .instructions = rp2040encoder_program_instructions,
    .length = 30,
    .origin = 0,
    .pio_version = rp2040encoder_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rp2040encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rp2040encoder_wrap_target, offset + rp2040encoder_wrap);
    return c;
}
#endif
