; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; *****************************************************************************
; Target environment for Zumo2040.
; *****************************************************************************

[hal:RP2040]
; We use this platform to get the right toolchain for the Earle Philhower
; (arduino-pico) core, which provides direct access to the Pico SDK in addition to
; the Arduino framework.
; For more information, see https://github.com/maxgerhardt/platform-raspberrypi
; and https://arduino-pico.readthedocs.io/en/latest/.
; For a comparison between the standard Mbed OS core and the arduino-pico core,
; see https://github.com/earlephilhower/arduino-pico/discussions/246
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
    -Wno-switch
    -Werror
lib_deps =
    BlueAndi/ZumoHALRP2040 @ ~0.5.0

; *****************************************************************************
; PC example environment
; *****************************************************************************

[env:Example]
extends = hal:RP2040
build_flags =
    ${hal:RP2040.build_flags}
lib_deps =
    ${hal:RP2040.lib_deps}